"""empty message

Revision ID: 62b4346be875
Revises: 
Create Date: 2024-07-05 15:02:41.332256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column, select, update
from sqlalchemy import String, Boolean, DateTime, Text
import json

# revision identifiers, used by Alembic.
revision = '62b4346be875'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('status_history')

    # ### end Alembic commands ###
