"""Fecha pago para los movimientos fijos

Revision ID: b2870dfafed8
Revises: 62b4346be875
Create Date: 2024-08-12 21:01:17.728924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = 'b2870dfafed8'
down_revision = '62b4346be875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fijo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_pago', sa.DateTime(), nullable=True))

    # Obtener la conexión de la base de datos
    connection = op.get_bind()

    # Ejecutar la sentencia SQL en bruto
    sql = text("""
    UPDATE fijo
    SET fecha_pago = (
        SELECT fecha
        FROM movimiento
        WHERE movimiento.id = fijo.id
    )
    """)
    connection.execute(sql)
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fijo', schema=None) as batch_op:
        batch_op.drop_column('fecha_pago')

    # ### end Alembic commands ###
